### ISSUE TITLE
ci: coverage uploads are broken

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pkcs11#161]
https://github.com/tpm2-software/tpm2-pkcs11/pull/160

`make check-code-coverage` is broken. It doesn't fail if make check fails. --enable-code-coverage is passed to ./configure for the final make check run, and I see gcov output. However, the upload fails as coverage.py to generate the xml report isn't present. This flow is very similar to TSS, not sure what they are doing differently.

**Comment by williamcroberts** [comment]
@joholl any ideas on this or the best way forward?

**Comment by joholl** [comment]
You're right. The `check-code-coverage` target does not propagate errors (and probably shouldn't). I noticed that for the TSS, travis never calls `make check-code-coverage` but only `make check`. It seems that `make check-code-coverage` is not what we want since it invokes `lcov` (which we do not need).

The configure switch `enable-code-coverage` is sufficient to have make pass the needed flags (`-fprofile-arcs` and `-ftest-coverage`) to the gcc compiler. As a result, the `.gcda` and `.gcno` files are generated. The bash script provided by codecov calls gcov which should process these files into `.gcov` files. However, it fails to do so: `Could not open output file '^#test#integration#<name-of-test>.int.c.gcov'`.

`make check-code-coverage` worked because `lcov` generated a report already. Although `gcov` failed, there was a report existing which was found by the codecov bash script.

Do you have any idea why `gcov` fails to write in travis?

For reverence: [travis log with gcov failing](https://travis-ci.org/joholl/tpm2-pkcs11/jobs/508818344#L3365)

**Comment by williamcroberts** [comment]
fixed in https://github.com/tpm2-software/tpm2-pkcs11/pull/185
