### ISSUE TITLE
ssh server support

### ISSUE THREAD

**Issue by vvug** [tpm2-software/tpm2-pkcs11#282]
Hi,

does this project support storing the ssh *server* key in the tpm? If not, is there any plan for it?

**Comment by williamcroberts** [comment]
I haven't tested it, but it should work.

**Comment by mdempsky** [comment]
I think OpenSSH only supports using PKCS#11 for client keys, not for server keys. I at least don't see any mention of "pkcs" in sshd_config.5.

**Comment by vvug** [comment]
Can't it be done using `HostKeyAgent`?

**Comment by mdempsky** [comment]
@vvug Ah, right. Yeah, in that case it looks doable.

One nit is that tpm2-pkcs11 *requires* a PIN on its tokens, and you might have some awkwardness providing the PIN to ssh-add in an automated manner. Looking at the source code, I think you'll have to set SSH_ASKPASS to a script that just prints the PIN to stdout, and then probably also set DISPLAY so that ssh-add is willing to use SSH_ASKPASS.

This is all OpenSSH tedium though. I think tpm2-pkcs11 should work equally well within ssh-agent operating either on the client or server side. As far as I can tell, ssh-agent can't tell / doesn't care whether it's being used for client or server keys.

**Comment by vvug** [comment]
Well, thanks! I'm closing this for now, and try to find the time to actually try this setup.
