### ISSUE TITLE
No need for python3 (it works with version 2.4)

### ISSUE THREAD

**Issue by jhealyt** [tpm2-software/tpm2-pkcs11#322]
The python file in the tools folder starts with this line:

`#!/usr/bin/env python3`

I spent quite a while upgrading (and then later downgrading) the python package on my embedded Linux device, but later I found out that all of these tools don't actually need python3. So that line can simply be:

`#!/usr/bin/env python`

**Comment by diabonas** [comment]
Currently the Python scripts are indeed [tested with Python 2 and 3](https://github.com/tpm2-software/tpm2-pkcs11/blob/e9e360b202bc410af52e556335976b474f6359e9/.travis.yml#L10-L11) in the CI. I am not sure how long Python 2 will be supported though since it will be [end-of-life at the end of this year](https://pythonclock.org/), also see https://github.com/tpm2-software/tpm2-tools/issues/1708. If I read the revised [PEP 394](https://www.python.org/dev/peps/pep-0394/) correctly, `python` is not required to exist on all systems (while either `python2` or `python3` must be available), so using `#!/usr/bin/env python` can potentially reduce portability.

**Comment by jhealyt** [comment]
I'm just reading now about how "/usr/bin/python" can be a symbolic link to "python2", however it will never be a symbolic link to "python3".

What a mess.

**Comment by diabonas** [comment]
That was the standard set by to old version of PEP 394. It has since been revised so that it can be either Python 2 or 3:

> Distributors may choose to set the behavior of the `python` command as follows:
> - `python2`,
> - `python3`,
> - not provide `python` command,
> - allow `python` to be configurable by an end user or a system administrator.

Arch Linux has been symlinking `python` to `python3` for quite some time, I haven't actually encountered a system yet that doesn't provide `python`, but only `python2`/`python3`.

**Comment by williamcroberts** [comment]
python2 is EOL at the end of the year, so moving forwards we will remove python 2 builds from the matrix. SE Linux just did this, so we'll probably follow suit.

**Comment by williamcroberts** [comment]
There's nothing for us to do here, so closing
