### ISSUE TITLE
SSHD use tpm2-pkcs11 with TPM key and non TPM key 

### ISSUE THREAD

**Issue by Roger886** [tpm2-software/tpm2-pkcs11#679]
does it possible to configure SSHd and tpm2-pkcs to use TPM reside key and also some of other key outside TPM? As TPM not able to support all key formats.
E.g., RSA and ecc key reside in TPM but ed25519/448 in disk

**Comment by diabonas** [comment]
You can combine host keys loaded from a `HostKeyAgent` (which is used to manage the tpm2-pkcs11 keys) and host keys stored on disk, e.g.
```
HostKey /etc/ssh/ssh_host_tpm
HostKeyAgent /root/.tpm2_pkcs11/ssh-agent.sock
HostKey /etc/ssh/ssh_host_ed25519_key
```
Here `/etc/ssh/ssh_host_tpm` is the public part of the key stored in the TPM, `/root/.tpm2_pkcs11/ssh-agent.sock` is the socket for the SSH agent used to manage the key backed by tpm2-pkcs11, and `/etc/ssh/ssh_host_ed25519_key` is a private key stored on disk as usual.

The SSH server will serve all these keys and let SSH clients choose which one they want to use for authentication. However, this is probably not what you want, because recent SSH clients will prefer the ed25519 key over the keys stored in the TPM (only one of the host keys is used at a time, not all of them). **This decreases security because many clients will use the on-disk keys as if the TPM was not there at all.**

**Comment by williamcroberts** [comment]
FYI someone did a write up on configuring this here: https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/SSH_HOSTKEYS.md

**Comment by williamcroberts** [comment]
I think this has been answered, closing.
