### ISSUE TITLE
Configure is failing

### ISSUE THREAD

**Issue by nagesh20** [tpm2-software/tpm2-pkcs11#69]
Thanks to  williamcroberts  for bootstrap LD_VERSION issue and  now i'm able to do successful bootstrap step with ./bootstrap -I /usr/share/gnulib/m4 .

configure throws below error
pi@raspberrypi:~/tpm2-pkcs11 $ ./configure
configure: error: Invalid policy. Valid policies: git-directory, minor-version.

For more information:
Platform : Raspberry Pi model 3 revB board
OS : Linux version 4.14.72-v7+ (root@raspberrypi) (gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1)) #8 SMP

**Comment by williamcroberts** [comment]
@nagesh20 I think that's the AX_IS_RELEASE macro failing on you. Not really sure why. Is your autoconf-archive most recent or old?

**Comment by nagesh20** [comment]
@williamcroberts  Yes i'm building from git directory. 

pi@raspberrypi:~/tpm2-pkcs11 $ sudo apt-get install autoconf
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version (2.69-10).
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
pi@raspberrypi:~/tpm2-pkcs11 $ sudo apt-get install autoconf-archive
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf-archive is already the newest version (20160916-1).
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.

pi@raspberrypi:~/tpm2-pkcs11 $ git remote -v
origin  https://github.com/tpm2-software/tpm2-pkcs11.git (fetch)
origin  https://github.com/tpm2-software/tpm2-pkcs11.git (push)
pi@raspberrypi:~/tpm2-pkcs11 $ git rev-parse HEAD
295aa291f3959202e7ccfbd5e45106f0095c6608
pi@raspberrypi:~/tpm2-pkcs11 $ git describe --always
295aa29

**Comment by williamcroberts** [comment]
Ahh you need to install a newer autoconf-archive, or copy the contents into the projects m4 directory (create if it doesn't exist)

http://mirror.team-cymru.com/gnu/autoconf-archive/autoconf-archive-2018.03.13.tar.xz

You should just be able to copy the m4 directory from that archive into the tpm2-pkcs11 project.

**Comment by nagesh20** [comment]
@williamcroberts  Thank you , it works now.  Closing issue.

**Comment by PeterHuewe** [comment]
Hi,
@williamcroberts :
I'd like to re-open this issue - it breaks the installation on a recent raspbian and thus probably on all debian stretch based  installations - which is annoying.
As a first time user or drive-by-contributor I *immediately* dismiss software if the bootstrap/configure fails for some obscure reasons.

Yes there is a workaround - but it also used to work in the past without problems.
If we want to have tpm2-pkcs11 packaged, we should come up with a suitable solution.
(e.g. use some less modern macros)

**Comment by williamcroberts** [comment]
> Hi,
> @williamcroberts :
> I'd like to re-open this issue - it breaks the installation on a recent raspbian and thus probably on all debian stretch based installations - which is annoying.
> As a first time user or drive-by-contributor I _immediately_ dismiss software if the bootstrap/configure fails for some obscure reasons.

Me too, but you should follow the building instructions of every project:
https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/BUILDING.md

I documented in length you need this version of autoconf-archive. The great thing is, you don't have to install it, no root required. You can just copy it to m4 dir for your build or another approach could be using -I option to bootstrap. The TSS libraries will have the same requirement soon, as they need to drop their copies of this. We shouldn't be distributing these m4 macros in our source tree nor carrying patches for them.

Debian stretch's packaged version is: 20160916
Since that their's been 3 releases and 2 years, with stretch version 9.6 being released on November 10th, 2018. They could have easily pulled in the latest, it's backwards compatible. But I am not sure of their policies of changing packaged versions for stable releases, my guess that its not allowed.

> 
> Yes there is a workaround - but it also used to work in the past without problems.
> If we want to have tpm2-pkcs11 packaged, we should come up with a suitable solution.
> (e.g. use some less modern macros)

You only need to satisfy this dependency for building, an actual packager can simply setup the m4 macro dependency and build a Debian package out. An actual Debian package in the package manager won't have any build time dependencies.

**Comment by rickydjohn** [comment]
Hi, I am still seeing this error when building on a deb-9 machine. I tried what was recommended by @williamcroberts.  That didn't seem to work in my case. 

![image](https://user-images.githubusercontent.com/12184141/58857510-16285f00-86c3-11e9-8f20-a166e2946175.png)

Thanks in advance for your support.

**Comment by PeterHuewe** [comment]
./bootstrap -I m4
