### ISSUE TITLE
Missing model name

### ISSUE THREAD

**Issue by kuba00739** [tpm2-software/tpm2-pkcs11#735]
Hello,

I have noticed that model name is missing in serialized ID:

`p11tool --list-all`
```
pkcs11:model=;manufacturer=STMicro;serial=0000000000000000;token=tpm2_ecc
```

It is quite problematic because openvpn can't handle this case. Do you know any workaround?

Thank you in advance

**Comment by niooss-ledger** [comment]
Hello,
Could you please share the precise behavior you are experiencing? Does "openvpn can't handle this case" means that it crashes (for example with an unexpected NULL pointer dereference or an assertion error) or that it reports an error message?

Also, does `openvpn --show-pkcs11-ids` work? Or `openvpn --show-pkcs11-ids /usr/lib/pkcs11/libtpm2_pkcs11.so` (replacing the path to the .so library with the one you are using)?

More generally, could you provide some steps which can help reproducing your issue? (how is openvpn configured, what commands are you trying to execute, etc.)

On the issue of "the model name is missing", the model reported by tpm2-pkcs11 directly comes from `TPM2_PT_VENDOR_STRING_...` properties: https://github.com/tpm2-software/tpm2-pkcs11/blob/862bdb845910342cd7b6e6da7495f6ee7d090a37/src/lib/tpm.c#L759-L766

Does your TPM contain empty values in these properties? A way of reading them consists in running `tpm2_getcap properties-fixed | grep -A2 TPM2_PT_VENDOR_STRING` (this command comes from project tpm2-tools).

**Comment by niooss-ledger** [comment]
@kuba00739 I tried to reproduce your issue in an Arch Linux container, using a patched software TPM in order to have an empty model. My OpenVPN setup works fine, so I was not able to reproduce your issue.

Here is the log which is generated on the client with `openvpn --verb 11`: [client_log.txt](https://github.com/tpm2-software/tpm2-pkcs11/files/7449406/client_log.txt)

For more details, here is what I did to get a software TPM with an empty model

- I started an Arch Linux container, which was able to use `/dev/tun` to start a VPN: `podman run --cap-add=NET_ADMIN --device /dev/net/tun --rm -ti docker.io/library/archlinux bash`
- I installed much software: `pacman --noconfirm -Syu openvpn openssh easy-rsa vim net-tools openssh tpm2-abrmd tpm2-tools autoconf-archive python-setuptools python-cryptography python-pyasn1-modules python-yaml sqlite tpm2-tss git vim zsh screen socat python net-tools asp base-devel wget opensc libp11 base-devel perl swtpm tpm2-pkcs11`
- I built and installed a patched version of package `libtpms`: `useradd --uid 1000 --user-group --create-home user && asp checkout libtpms && cd libtpms/repos/community-x86_64/ && chown user . && sudo -u user makepkg -o --skippgpcheck && vim src/libtpms/src/tpm2/VendorString.h` then modify `VENDOR_STRING_1` and `VENDOR_STRING_2` to `"\0\0\0\0"`, `sudo -u user PATH=/usr/bin/core_perl/:/usr/bin:/usr/sbin makepkg -e && pacman -U --noconfirm libtpms-0.9.0-1-x86_64.pkg.tar.zst`
- I started a software TPM and a tpm2-abrmd service (which uses DBus): `swtpm_setup --tpm2 --create-ek-cert --tpm-state /tmp && swtpm socket --tpm2 --server port=2321 --daemon --ctrl type=tcp,port=2322 --flags not-need-init --tpmstate dir=/tmp --log file=/tmp/swtpm.log,level=5 && mkdir -p /run/dbus && dbus-daemon --system --fork && tpm2-abrmd --allow-root --tcti swtpm:host=127.0.0.1,port=2321 &`
- I defined some TCTI: `export TPM2_PKCS11_TCTI=tabrmd:bus_type=system`, `export TPM2TOOLS_TCTI=tabrmd:bus_type=system`
- I provisioned the TSS2 part of the software TPM: `tss2_provision`

In this setup, I got:

```console
$ tpm2_getcap properties-fixed
...
TPM2_PT_MANUFACTURER:
  raw: 0x49424D00
  value: "IBM"
TPM2_PT_VENDOR_STRING_1:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_STRING_2:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_STRING_3:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_STRING_4:
  raw: 0x0
  value: ""
```

I Then created an ECC key with tpm2-ptools and a CSR for OpenVPN:

```console
$ tpm2_ptool init
action: Created
id: 1

$ tpm2_ptool addtoken --pid=1 --label=ssh --userpin=XXXX --sopin=YYYY
$ tpm2_ptool addkey --label=ssh --userpin=XXXX --algorithm=ecc256
$ p11tool --list-token-urls
pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust
pkcs11:manufacturer=IBM;serial=0000000000000000;token=ssh
pkcs11:manufacturer=IBM;serial=0000000000000000;token=

$ TOKEN='pkcs11:manufacturer=IBM;serial=0000000000000000;token=ssh'
$ GNUTLS_PIN=XXXX p11tool --login --list-all "$TOKEN"
WARNING: Needed CKA_VALUE but didn't find encrypted blob
Object 0:
	URL: pkcs11:manufacturer=IBM;serial=0000000000000000;token=ssh;id=%31%33%66%63%63%31%39%38%62%33%34%62%64%61%61%63;type=private
	Type: Private key (EC/ECDSA-SECP256R1)
	Label: 
	Flags: CKA_PRIVATE; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
	ID: 31:33:66:63:63:31:39:38:62:33:34:62:64:61:61:63

Object 1:
	URL: pkcs11:manufacturer=IBM;serial=0000000000000000;token=ssh;id=%31%33%66%63%63%31%39%38%62%33%34%62%64%61%61%63;type=public
	Type: Public key (EC/ECDSA-SECP256R1)
	Label: 
	ID: 31:33:66:63:63:31:39:38:62:33:34:62:64:61:61:63

$ PRIVATE_KEY=pkcs11:manufacturer=IBM;serial=0000000000000000;token=ssh;id=%31%33%66%63%63%31%39%38%62%33%34%62%64%61%61%63;type=private
$ cat > client.cnf << EOF
[ req ]
default_bits           = 2048
distinguished_name     = req_distinguished_name
prompt                 = no
[ req_distinguished_name ]
C                      = US
ST                     = Internet
L                      = Network
O                      = Widget Co
OU                     = Internet of Widgets Group
CN                     = $(uname -n)
EOF

$ openssl req -new -engine pkcs11 -keyform engine -key "${PRIVATE_KEY};pin-value=XXXX" -config client.cnf -out client.csr
```

Then, I configured a test OpenVPN server, signed the certificate signing request and started the server.

<details>

```sh
mkdir /server
cd /server

easyrsa init-pki
cp /etc/easy-rsa/openssl-easyrsa.cnf pki/openssl-easyrsa.cnf
ln -s /etc/easy-rsa/x509-types pki/x509-types

# CA Key Passphrase
echo -e 'secret\nsecret\n' | easyrsa build-ca
echo | easyrsa gen-req server nopass
echo -e 'yes\nsecret' | script -qc 'easyrsa sign-req server server' /dev/null
easyrsa gen-dh

cp /usr/share/openvpn/examples/server.conf pki/private/server.key pki/issued/server.crt pki/ca.crt .
cp pki/dh.pem dh2048.pem
openvpn --genkey secret ta.key

# Change : proto tcp, disable "explicit-exit-notify 1" in server.conf

# Sign the client CSR
easyrsa import-req /client.csr client
echo -e 'yes\nsecret' | script -qc 'easyrsa sign-req client client' /dev/null
cp /server/pki/issued/client.crt /
cp /server/ca.crt /server/ta.key /

# Start the OpenVPN server
openvpn --config server.conf --verb 11
```
</details>

Then I imported the signed certificate in tpm2-pkcs11 database:

```console
$ cd /
$ KEY_ID="$(echo 31:33:66:63:63:31:39:38:62:33:34:62:64:61:61:63 | sed 's/://g')" ; echo $KEY_ID
31336663633139386233346264616163
$ tpm2_ptool addcert --label=ssh --key-id=${KEY_ID} ./client.crt
action: add
cert:
  CKA_ID: '31336663633139386233346264616163'

$ openvpn --show-pkcs11-ids /usr/lib/pkcs11/libtpm2_pkcs11.so

The following objects are available for use.
Each object shown below may be used as parameter to
--pkcs11-id option please remember to use single quote mark.

Certificate
       DN:             C=US, ST=Internet, L=Network, O=Widget Co, OU=Internet of Widgets Group, CN=a31742585c99
       Serial:         01B3A0F390A8FA3A5AE553CDBB60CF63
       Serialized id:  IBM//0000000000000000/ssh/31336663633139386233346264616163
```

(See that there is no model in the Serialized id).

Finally I started the client by copying `/usr/share/openvpn/examples/client.conf`, removing `key`, `cert` and `remote` options there, and running:

```sh
openvpn --config client.conf --verb 11 --nobind --remote '127.0.0.1' --proto tcp --pkcs11-providers /usr/lib/pkcs11/libtpm2_pkcs11.so --pkcs11-id 'IBM//0000000000000000/ssh/31336663633139386233346264616163'
```

... which led to the attached log file, [client_log.txt](https://github.com/tpm2-software/tpm2-pkcs11/files/7449406/client_log.txt).

<details>
<summary>Package list</summary>

```text
libtpms 0.9.0-1
swtpm 0.6.1-1
tpm2-abrmd 2.4.0-1
tpm2-pkcs11 1.7.0-2
tpm2-tools 5.2-1
tpm2-tss 3.1.0-1

openvpn 2.5.4-1
opensc 0.22.0-1
openssl 1.1.1.l-1

libp11 0.4.11-1
libp11-kit 0.24.0-2
p11-kit 0.24.0-2
pkcs11-helper 1.27.0-2
```
</details>

I hope these details will help you finding in which component the issue occurs on your system.
